### ISSUE TITLE
Debian 12 install error

### ISSUE THREAD

**Issue by kszabi777** [kelebek333/rtl8192fu-dkms#9]
Hello,

Driver installation is not working under Debian 12.

------------------------------------------------------------------------------------------------------

root@debian:/var/lib/dkms/rtl8192fu/5.8.6.2/build# uname -r
6.1.0-13-amd64

------------------------------------------------------------------------------------------------------

root@debian:~# dkms build rtl8192fu/5.8.6.2
Sign command: /usr/lib/linux-kbuild-6.1/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
'make' all KVER=6.1.0-13-amd64....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.0-13-amd64 (x86_64)
Consult /var/lib/dkms/rtl8192fu/5.8.6.2/build/make.log for more information.

------------------------------------------------------------------------------------------------------

root@debian:/var/lib/dkms/rtl8192fu/5.8.6.2/build# cat make.log
DKMS make.log for rtl8192fu-5.8.6.2 for kernel 6.1.0-13-amd64 (x86_64)
Fri Dec  8 04:17:04 PM CET 2023
/bin/sh: 1: bc: not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.1.0-13-amd64/build M=/var/lib/dkms/rtl8192fu/5.8.6.2/build  modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-13-amd64'
/bin/sh: 1: bc: not found
  CC [M]  /var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_debug.o
/var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_debug.c: In function ‘dump_drv_version’:
/var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_debug.c:45:69: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
   45 |         RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                                     ^
In file included from /var/lib/dkms/rtl8192fu/5.8.6.2/build/include/drv_types.h:60,
                 from /var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_debug.c:17:
/var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_debug.c:45:51: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
   45 |         RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                   ^~~~~~~~
/var/lib/dkms/rtl8192fu/5.8.6.2/build/include/rtw_debug.h:224:46: note: in definition of macro ‘RTW_PRINT_SEL’
  224 |                         _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                                              ^~~
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-13-common/scripts/Makefile.build:255: /var/lib/dkms/rtl8192fu/5.8.6.2/build/core/rtw_debug.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-13-common/Makefile:2039: /var/lib/dkms/rtl8192fu/5.8.6.2/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-13-amd64'
make: *** [Makefile:2328: modules] Error 2

------------------------------------------------------------------------------------------------------

Could you please fix it ?

**Comment by kszabi777** [comment]
BC was missing, after installation the code is working!
